### ISSUE TITLE
Separator formatting needs adjusted

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#107]
Separator formatting is a bit strange. When you change the color, it currently retains the black central line. It also doesn't actually format as "dots" or "wide."

Examples: https://sandbox.library.ucdavis.edu/separators/ 

Screenshot:
![Screen Shot 2022-05-26 at 9 47 35 AM](https://user-images.githubusercontent.com/17831969/170535375-0071acf1-b795-4bf2-820e-65e3cf07fae8.png)

Separators should 
- not have a black color in the middle
- actually be dotted when dots are selected
- be available in brand colors (same colors as what is allowed for "Panel with Icon" fine)

**Comment by spelkey-ucd** [comment]
This is a good first issue. 

What is currently happening is that we are extending the native wordpress separator block, and just slapping a basic patternLab class on it. As a result, the native wordpress styles and our brand styles are fighting. hence the problems!

So, the best solution is going to be:
1. disabling the native wp block
2. building our own custom block

Based on Kimmy's requests, our block should allow the user to:
1. select a style (solid or dotted)
2. select a thickness (normal or fat)
3. select a brand color (you will use the `toolbar-color-picker.js` custom component for this)

You can construct classes from the block attributes (`brandColor`, `style`,  `weight`). This is not very complicated, so no need to make a Lit Element; staying in React will be fine. One gotcha: React uses `className` instead of `class` when [applying styles.](https://reactjs.org/docs/faq-styling.html)

**Comment by UcDust** [comment]
Maybe we could also combine the style and thickness into a single block control, like have a dropdown with options like-

- Normal Solid
- Normal Dotted
- Wide Solid
- Wide Dotted

**Comment by wrenaria** [comment]
@UcDust If you can use the current icon, that's fine. If you can't, let me know, I can make one.

Since we're making a custom block solution, I am okay with simplifying separator line styles to just normal or dotted. Normal being 1px solid and dotted being ~4px dotted.

Example of dotted look I'm aiming for from a design mockup:
![Screen Shot 2022-05-31 at 10 37 14 AM](https://user-images.githubusercontent.com/17831969/171242233-ade535f3-ad70-411d-8bc4-fba59298a0dd.png)

**Comment by UcDust** [comment]
Perfect, thanks you two!

So it sounds like the main separator icon could be used for the separator, and we'll just need an icon for the normal vs dotted block control icon. Could we repurpose one of the icons from WP for that, or would you prefer something custom @wrenaria?

**Comment by UcDust** [comment]
Actually it looks like we have a format-size icon that might make sense for normal vs dotted, it's just a down arrow-

![border style](https://user-images.githubusercontent.com/103536473/171258902-bd4a46b8-2e9a-41db-b7e5-33b5252879f0.png)

**Comment by UcDust** [comment]
Hi @spelkey-ucd,
We've committed the [latest code to here](https://github.com/UCDavisLibrary/ucdlib-theme-wp/tree/dc-sb-separator-block). 
The editor and twig side seem to function well, but we're curious how you'd like to disable the core separator block? It looks like there are some plugins that could accomplish it, or [the WP docs](https://developer.wordpress.org/reference/hooks/allowed_block_types_all/) mention the `allowed_block_types_all` hook. Or perhaps there's another method that you would prefer?

**Comment by spelkey-ucd** [comment]
Yup, you would use the wordpress hook. I already have it all wired up, so you just need to add it to this array: https://github.com/UCDavisLibrary/ucdlib-theme-wp/blob/sandbox/theme/includes/classes/blocks.php#L201

**Comment by UcDust** [comment]
Thanks! Will do

**Comment by spelkey-ucd** [comment]
@UcDust really great work! Just needed to make it so that the separator can have its own color palette (from theme colors). The way you had it set up, it was using the `priority link` palette. If you go to `Appearance->Customize->Colors`, you can set subset the colors on a per-block basis. Now there is a Select box for separator.

You can see the changes I made in [this commit](https://github.com/UCDavisLibrary/ucdlib-theme-wp/commit/bdde3611a33ef5ce93940e1f5d71257dabbd59eb).

**Comment by UcDust** [comment]
Oops, sorry about that! Definitely a team effort :)

**Comment by wrenaria** [comment]
Looks good, but make sure color palette is limited the same options used in "Panel with Icon" as I don't want all possible brand colors available for this feature.

**Comment by UcDust** [comment]
It looks correct on sandbox though? @spelkey-ucd mentioned it's a GUI setting which controls the available colors, that may need to be changed.

**Comment by spelkey-ucd** [comment]
yup. just updated the palette on stage.

**Comment by wrenaria** [comment]
Looks good, thank you!

**Comment by spelkey-ucd** [comment]
@UcDust @sbagg 

Kimmy has requested that y axis margins be customizable. Specifically, she wants a 1rem option.

**Comment by spelkey-ucd** [comment]
Yeah, that's what i was thinking. I made a new component for toolbar dropdowns you can use: https://github.com/UCDavisLibrary/ucdlib-theme-wp/blob/sandbox/src/editor/lib/block-components/toolbar-select-menu.js

**Comment by wrenaria** [comment]
@UcDust Yes, like that! Use the same language as in your example above (1x, 2x), but keep 2x as default.

**Comment by UcDust** [comment]
Thanks @wrenaria @spelkey-ucd!

The control looks like this, and defaults to 2x-
![separator control](https://user-images.githubusercontent.com/103536473/178555796-d4d00084-6272-4494-8e36-e7314ad50b8c.png)

And the margin is 1rem top/bottom for 1x and 2rem top/bottom for 2x, is that ok?-
![separator spacing](https://user-images.githubusercontent.com/103536473/178555787-9ad006b6-3072-4b02-a38e-3d032fbad0b3.png)
