### ISSUE TITLE
Google Maps Block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#124]
We need a block to display a location on a google map: 

<img width="753" alt="image" src="https://user-images.githubusercontent.com/34284106/172909532-debc4819-68a2-4909-ada6-ca716eff8d97.png">

from: 

https://xd.adobe.com/view/6d90f413-ef9f-4490-b82f-00e57098540f-38c3/screen/c8e7c415-dbbd-44a7-8d74-b9f7a237c5f8/

No need to get very fancy with it, I think just an iframe will suffice:
https://developers.google.com/maps/documentation/embed/embedding-map

attributes will probably be:
- marker location
- width (default to 100%)
- height (default to 300ish?)

**Comment by UcDust** [comment]
@spelkey-ucd

Do we already have an API key generated for this by chance? 

It looks like my permissions for the digital-ucdavis-edu GCP project don't allow me to create a new key, so if we don't have one generated, I might need yours or @jrmerz help creating it.

**Comment by UcDust** [comment]
@spelkey-ucd @wrenaria 

For the width and height attributes, should we just have a dropdown block control for them with a few different options? Or how much flexibility should we be providing there?

**Comment by UcDust** [comment]
Here's a sample of what the editor side could look like. @wrenaria I'm not sure if using the standard map pointer icon is sufficient for the block in general as well as to use as a block control to edit the marker location, you can see that in the controls of the screenshot-
![Screen Shot 2022-06-21 at 10 57 50 AM](https://user-images.githubusercontent.com/103536473/174867112-a3cf9911-1f4f-4557-9d94-40c179b73d63.png)

One other property we arbitrarily set was having a _sm / md / lg_ dropdown control that allows a few orientations-

- sm: 33% width by 200px height
- md: 50% width by 300px height
- lg (default): 100% width by 300px height

These could be adjusted, or more controls / flexibility could be added if you'd like.

**Comment by wrenaria** [comment]
@UcDust What I see above looks okay to me! I'm not sure that we need any customization of size, full width at 300px height is fine. Maps will likely only live on the location page.

**Comment by UcDust** [comment]
Thanks @wrenaria! I've updated that.

**Comment by wrenaria** [comment]
@UcDust I see 3 things to adjust:

1. 300px sounded good in theory, but [looking at it in practice](https://sandbox.library.ucdavis.edu/map-and-social/), I don't like it. Feels too narrow at all device sizes. Let's increase the iframe height to 400px.

2. When text is placed next to the map using a column, it doesn't align nicely due to the padding at the top. Removing the padding will solve that.
![Screen Shot 2022-06-27 at 5 03 37 PM](https://user-images.githubusercontent.com/17831969/176059347-3f7d6ed6-5743-48de-9035-f018d611b3a8.png)


3. Is it possible for the default zoom of the map to be more zoomed in so you can see the outline of the library building?
