### ISSUE TITLE
Marketing Highlight (reg + horizontal) blocks needs vertical margin added

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#85]
Marketing Highlight and Marketing Highlight Horizontal blocks need vertical margin between them so that they aren't touching. Examples below.

## Marketing Highlight Horizontal example from [ASC Collections](https://stage.library.ucdavis.edu/archives-and-special-collections/collections/):

![Screen Shot 2022-03-29 at 12 00 04 PM](https://user-images.githubusercontent.com/17831969/160685747-9ec9fdc3-05d1-4987-8350-e9eadf3549ed.png)

## Marketing Highlight ([our site](https://stage.library.ucdavis.edu/archives-and-special-collections/) left vs [SiteFarm](https://biology.ucdavis.edu/) right):

![Screen Shot 2022-03-29 at 12 03 03 PM](https://user-images.githubusercontent.com/17831969/160686611-d4902956-ee34-481d-8c7e-3d60d2c639d8.png)

**Comment by wrenaria** [comment]
It seems like a lot of things are pretty tight together (space between content and sidebar, vertical space between end of paragraph text and header) so a broad look at that may be a good idea.

**Comment by spelkey-ucd** [comment]
The issue is that sitefarm wraps a lot of blocks in [panel](http://dev.webstyleguide.ucdavis.edu/redesign/?p=molecules-panel) and [o-box](http://dev.webstyleguide.ucdavis.edu/redesign/?p=molecules-o-box) classes, which add bottom margin and padding, respectively. So, everything is more spaced out. It's not a global layout thing, but on the blocks themselves:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/34284106/161086752-90ee2f01-8f85-4b5b-9dc3-1485d2245638.png">


As for solutions:
We have an `Object Box` block, which adds padding, and optionally bottom margins, and then you can put any blocks you want inside. (screenshot below)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/34284106/161084370-3bcae1cb-b620-4f40-afc5-b4be50c26579.png">

I think it would be a pain, and unrealistic to expect our users to manually wrap all their blocks in the `Object Box`, so I'm going to add padding and bottom margins automatically to a lot of the blocks (marketing highlights, posters, subnavs, etc). 

However, in some cases we will still have to use the `Object Box` block. For example, your Inclusion and Equity group block since it is composed of multiple blocks (title, paragraph, icon link).
